---
# tasks file for /home/ec2-user/ansible/roles/common
- name: Common Tasks
  debug:
    msg: Common Task Triggered

- name: Fix dpkg
  command: dpkg --configure -a

- name: Update apt
  apt:
    upgrade: dist
    update_cache: yes

- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ntp